language: java

sudo: required

jdk:
  - oraclejdk8

before_install:
  - chmod +x mvnw

install: true

script:
  - ./mvnw clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      - araknoid@gmail.com
    on_success: always # default: change [always|never|change]
    on_failure: always # default: always [always|never|change]